name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
      - feature/*

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # Paso 2: Cache pip
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Paso 3: Configurar Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Paso 4: Instalar dependencias de pruebas
      - name: Install dependencies for testing
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-test.txt

      # Paso 5: Ejecutar tests
      - name: Run Model Tests
        run: |
          pytest --cov=challenge --cov-report=term --cov-report=html:reports/html --cov-report=xml:reports/coverage.xml tests/model/test_model.py

      - name: Run API Tests
        run: |
          pytest --cov-config=.coveragerc --cov-report term --cov-report html:reports/html --cov-report xml:reports/coverage.xml --junitxml=reports/junit.xml --cov=challenge tests/api/test_api.py

      # Paso 6: Subir reportes de pruebas (opcional)
      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: reports/